  0%|          | 0/6 [00:00<?, ?it/s]/root/fed_sim/venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:143: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
 17%|█▋        | 1/6 [02:45<13:45, 165.09s/it] 17%|█▋        | 1/6 [05:46<28:50, 346.18s/it]
Traceback (most recent call last):
  File "/root/fed_sim/src/main.py", line 165, in <module>
    local_models[idx].save_model(model_output_dir, suffix="agent_" + str(idx), step=epoch)
  File "/root/fed_sim/src/models.py", line 98, in save_model
    torch.save(
  File "/root/fed_sim/venv/lib/python3.10/site-packages/torch/serialization.py", line 627, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/root/fed_sim/venv/lib/python3.10/site-packages/torch/serialization.py", line 501, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/root/fed_sim/venv/lib/python3.10/site-packages/torch/serialization.py", line 472, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: Parent directory save/06-07_17:02_423429dirich_False_dec-True_ED-False_pe0.1_a20_e96_le16.0 does not exist.
